# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://text-lucene.services.istex.fr

###
# @name v1IstexSearch
# Construit une requête syntaxe Lucene à partir d'une requête en langue naturelle (quelle que soit la langue).
POST {{host}}/v1/istex-search?indent=true HTTP/1.1
Content-Type: application/json

[
	{
		"value": "Je veux un corpus d'articles scientifiques publiés post 2020 sur la biodiversité dans la méditerranée nord. Les documents seront en anglais"
	},
	{
		"value": "no query"
	}
]
