# OpenAPI Documentation - JSON format (dot notation)
post.responses.default.description = reformulate
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.summary = Reformule les questions
post.requestBody.required = true
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.parameters.0.in = query
post.parameters.0.name = path
post.parameters.0.schema.type = string
post.parameters.0.description = The path in each object to enrich with a Python script
post.parameters.1.in = query
post.parameters.1.name = indent
post.parameters.1.schema.type = boolean
post.parameters.1.description = Indent or not the JSON Result
post.parameters.2.in = query
post.parameters.2.name = type
post.parameters.2.schema.type = string
post.parameters.2.description = Type de traitement RAG (Choix : Rag ou definition)


[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = env('path', 'value')
size = 100
# in production mode, uncomment the following line
# cache = boost

[expand/exec]
# command should be executable !
command = ./v1/reformulate.py
args = fix('-p')
args = env('type', "rag")

[dump]
indent = env('indent', false)