# These examples can be used directly in VSCode, using REST Client extension (humao.rest-client)

# Décommenter/commenter les lignes voulues pour tester localement
@baseUrl=http://localhost:31976
# @baseUrl=https://base-line.services.istex.fr

###
# Parse un flux JSON, et le returne sans modification
POST {{baseUrl}}/v1/no-accent?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "é" },
	{ "value": "à" }
]

###
