# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
# @host=http://localhost:31976
@host=https://irc3-species.services.istex.fr

###
# @name v1routeInCamelCase
# Description de la route
POST {{host}}/v1/irc3sp?indent=true HTTP/1.1
Content-Type: application/json

[
  {
    "id": 1,
    "value": "Trophic diversity accumulation curves of (a) Pseudopercis semifasciata, (b) Acanthistius patachonicus and (c) Pinguipes brasilianus. Horizontal lines show Brillouin diversity index (Hz) values (Hz± 0·05 Hz) and the vertical line shows a value n- 2 (n = number of stomachs)."
  },
  {
    "id": 2,
    "value": "Phasianus colchicus/versicolor: in our study, the best match."
  },
  {
    "id": 3,
    "value": "short lower jaw in Etheostoma bellator Suttkus"
  }
]
