# OpenAPI Documentation - JSON format (dot notation)
mimeType = text/plain

post.operationId = post-v1-istexsearch-txt
post.summary = Assistance à la génération de requête Lucene dans Istex Search
post.description = Génère une requête en syntaxe Lucene a partir d'une requête en langue naturelle (service multilingue). La sortie est au format `txt`.
post.tags.0 = text-lucene

# post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.content.text/plain.schema.type = string
post.requestBody.content.text/plain.schema.description = Requête en texte brut pour la génération Lucene

post.requestBody.required = true
post.responses.default.content.text/plain.schema.type = string
post.responses.default.content.text/plain.schema.description = Requête Lucene générée au format texte brut

# Examples
post.requestBody.content.text/plain.example = Je veux un corpus d'articles scientifiques publiés post 2000 sur la biodiversité dans la méditerranée nord. Les documents seront en anglais.
post.responses.default.content.text/plain.example = (title:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity") OR abstract:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity") OR subject.value:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity")) AND (title:("north mediterranean" "north mediterranean sea") OR abstract:("north mediterranean" "north mediterranean sea") OR subject.value:("north mediterranean" "north mediterranean sea")) AND language.raw:("eng") AND genre.raw:"research-article" AND publicationDate:[2000 TO *]
#'

[use]
plugin = @ezs/spawn
plugin = @ezs/basics
plugin = @ezs/analytics

[exchange]
value = thru(m => m+"\n")

[TXTParse]

[TXTObject]

[remove]
test=get("value").isEmpty()

[exec]
# command should be executable !
command = ./v1/istex-search.py

[assign]
path = value
value = get("value").thru(m => m+"\n")

[value]
