# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.operationId = post-v1-istex-search
post.summary = Assistance à la génération de requête Lucene dans Istex Search
post.description = Génère une requête en syntaxe Lucene a partir d'une requête en langue naturelle (service multilingue)
post.tags.0 = text-lucene
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.required = true
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.responses.default.description = Le champ `value` contient la requête Lucene générée
post.parameters.0.description = Indenter le JSON résultant
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean

# Examples
post.requestBody.content.application/json.example.0.value = Je veux un corpus d'articles scientifiques publiés post 2020 sur la biodiversité dans la méditerranée nord. Les documents seront en anglais
post.requestBody.content.application/json.example.1.value = no query
post.responses.default.content.application/json.example.0.value = (title:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity") OR abstract:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity") OR subject.value:("biodiversity" "marine biodiversity" "ocean biodiversity" "oceanic biodiversity")) AND (title:("north mediterranean" "north mediterranean sea") OR abstract:("north mediterranean" "north mediterranean sea") OR subject.value:("north mediterranean" "north mediterranean sea")) AND language.raw:("eng") AND genre.raw:"research-article" AND publicationDate:[2020 TO *]
post.responses.default.content.application/json.example.1.value = 

[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 5

[expand/exec]
# command should be executable !
command = ./v1/istex-search.py

[dump]
indent = env('indent', false)
