# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.operationId = post-v1-embed-small-text
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.required = true
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.responses.default.description = Embeddings du texte envoyé (tableau de nombres)
post.summary = Calcule les embeddings de petits textes (sans les découper)
post.description = Calcule les embeddings de petits textes (sans les découper). Utilise le modèle [`all-MiniLM-L6-v2`](https://huggingface.co/Xenova/all-MiniLM-L6-v2).
post.tags.0: embeddings-computer
post.parameters.0.description = Indenter le JSON résultant
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.required = false
post.parameters.0.schema.type = boolean

# Examples
post.requestBody.content.application/json.example.0.value = This is a test text for the embeddings model. It should be able to handle multiple texts at once.
post.requestBody.content.application/json.example.2.value = Et maintenant, je mets une phrase en français.

[use]
plugin = @ezs/basics
plugin = @ezs/spawn

[JSONParse]
separator = *

[expand]
path = value
size = 100

[expand/exec]
# command should be executable !
command = ./embed-local.mjs

[dump]
indent = env('indent', false)
