# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.operationId = post-v1-anonymize
post.summary = Anonymiseur de texte
post.description = Anonymise les données personnelles d'un texte.
post.tags.0 = text-anonymize
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.required = true
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.responses.default.description = Le champ `value` contient le texte anonymisé
post.parameters.0.description = Indenter le JSON résultant
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean
post.parameters.1.description = Langue
post.parameters.1.in = query
post.parameters.1.name = lang
post.parameters.1.schema.type = string
post.requestBody.content.application/json.example.0.id = 1
post.requestBody.content.application/json.example.0.value = Sex: M - Email: john.smith@example.com - Phone: (212) 555-0198 - City: Bristol, SW1A 1AA\nHello, my name is John Smith and I live in Bristol.
post.responses.default.content.application/json.example.0.id = 1
post.responses.default.content.application/json.example.0.value = Sex: [SEX] - Email: [EMAIL] - Phone: [TEL] - City: [CITY]\nHello, my name is [PERSON] and I live in [LOCATION].

[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 100

[expand/exec]
# command should be executable !
command = ./v1/anonymize.py
args = fix('-p')
args = env('lang', "en")

[dump]
indent = env('indent', false)