# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://person-ner.services.istex.fr

###
# @name v1Tagger
# Extraction d'entités nommées de nom de personnes (multilingue)
POST {{host}}/v1/tagger?indent=true HTTP/1.1
Content-Type: application/json

[
  {
    "id": "1",
    "value": "Python is widely used in data science. Bob R. uses it ; he works for the CNRS"
  },
  {
    "id": "2",
    "value": "Jean Dupont assiste àu festival de Cannes sur la côte d'Azur."
  }
]

###
# @name v1TaggerEn
# Extraction d'entités nommées de nom de personnes (Anglais)
POST {{host}}/v1/tagger-en?indent=true HTTP/1.1
Content-Type: application/json

[
  {
    "id": 1,
    "value": "On September 15th, 2023, the renowned artist Sarah Blake unveiled Whispers of the Wind, at the Metropolitan Museum of Art in New York City. The event attracted people from all over the world, including the famous author Emily Green and several political figures from the United Nations. The museum, located on Fifth Avenue, is known for its extensive collection of European paintings. During the unveiling, a new highway connecting the city to Washington, D.C., was also announced, funded by a grant of $5 million from the federal government. This new project, expected to be completed by 2025, promises to reduce travel time by 30%. Sarah's masterpiece, inspired by the serene landscapes of the Rocky Mountains, is expected to be a major attraction, drawing art enthusiasts and tourists alike."
  },
  {
    "id": 2,
    "value":"In April 2024, a groundbreaking technology summit was held at the Silicon Valley headquarters of FutureTech, attracting tech innovators and CEOs from major companies like OmniCorp and QuantumSoft. The keynote speaker, David Johnson, introduced Electra's latest product, an electric truck named CyberHauler. The summit, which lasted three days, highlighted advances in AI and green energy. Representatives from the European Union were present to discuss new environmental laws aimed at reducing carbon emissions by 20% over the next decade. The summit's discussions, conducted primarily in English, also touched on the upcoming Mars mission scheduled for 2030, which aims to establish the first human colony on the Red Planet. The event concluded with a gala dinner at the Golden Gate Bridge, with a spectacular view of the Pacific Ocean."
  }
]
