# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.operationId = post-v1-translit-hel-t2
post.summary = Translittérer de grec en latin (ISO 843 + diphtongues)
post.description = Translittère une chaîne de caractères grecs en une chaîne de caractères latins suivant la norme ISO 843 avec des règles supplémentaires sur les diphtongues.
post.tags.0 = transli-tal
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.required = true
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.responses.default.description = Les caractères grecs sont remplacés par leurs équivalents latins.
post.parameters.0.description = Indenter le JSON résultant
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean

post.requestBody.content.application/json.example.0.id = 1
post.requestBody.content.application/json.example.0.value = 1920-2020: ένας αιώνας δημογραφικής και κοινωνικής εξέλιξης των αιγαιακών κοινωνιών / Βασίλειος Σ. Γαβαλάς
post.requestBody.content.application/json.example.1.id = 2
post.requestBody.content.application/json.example.1.value = Γεωργίου Σ. Φραγκούδη
post.requestBody.content.application/json.example.2.id = 3
post.requestBody.content.application/json.example.2.value = Το ελληνικό χειρόγραφο βιβλίο (12ος-20ος αιώνας)
post.requestBody.content.application/json.example.3.id = 4
post.requestBody.content.application/json.example.3.value = Αιτήματα και πραγματικότητες των Ελλήνων της βενετοκρατίας (1554-1600)
post.requestBody.content.application/json.example.4.id = 5
post.requestBody.content.application/json.example.4.value = Εύθυμα διηγήματα
post.requestBody.content.application/json.example.5.id = 6
post.requestBody.content.application/json.example.5.value = Ο Ούγος Φώσκολος και η Ελληνική Επανάστασις
post.requestBody.content.application/json.example.6.id = 7
post.requestBody.content.application/json.example.6.value = Τροπή των συμφώνων ΤΣ και ΤΖ εις Σ και Ζ εις τα νότια ιδιώματα της νέας ελληνικής
post.requestBody.content.application/json.example.7.id = 8
post.requestBody.content.application/json.example.7.value = ΚΡΙΤΙΚΗ ΕΙΚΑΣΤΙΚΩΝ ΤΕΧΝΩΝ Α ΤΟΜΟΣ
post.requestBody.content.application/json.example.8.id = 9
post.requestBody.content.application/json.example.8.value = ΧΩΜΕΝΙΔΗΣ Χ. Α.
post.requestBody.content.application/json.example.9.id = 10
post.requestBody.content.application/json.example.9.value = Η πρώιμη οθωμανική τέχνη και αρχιτεκτονική στην Ελλάδα (14ος-16ος αιώνας)
post.responses.default.content.application/json.example.0.id = 1
post.responses.default.content.application/json.example.0.value = 1920-2020: énas aiṓnas dīmografikī́s kai koinōnikī́s exélixīs tōn aigaiakṓn koinōniṓn / Vasíleios S. Gavalás
post.responses.default.content.application/json.example.1.id = 2
post.responses.default.content.application/json.example.1.value = Geōrgíou S. Fragkoúdī
post.responses.default.content.application/json.example.2.id = 3
post.responses.default.content.application/json.example.2.value = To ellīnikó cheirógrafo vivlío (12os-20os aiṓnas)
post.responses.default.content.application/json.example.3.id = 4
post.responses.default.content.application/json.example.3.value = Aitī́mata kai pragmatikótītes tōn Ellī́nōn tīs venetokratías (1554-1600)
post.responses.default.content.application/json.example.4.id = 5
post.responses.default.content.application/json.example.4.value = Éfthyma diīgī́mata
post.responses.default.content.application/json.example.5.id = 6
post.responses.default.content.application/json.example.5.value = O Oúgos Fṓskolos kai ī Ellīnikī́ Epanástasis
post.responses.default.content.application/json.example.6.id = 7
post.responses.default.content.application/json.example.6.value = Tropī́ tōn symfṓnōn TS kai TZ eis S kai Z eis ta nótia idiṓmata tīs néas ellīnikī́s
post.responses.default.content.application/json.example.7.id = 8
post.responses.default.content.application/json.example.7.value = KRITIKĪ EIKASTIKŌN TECHNŌN A TOMOS
post.responses.default.content.application/json.example.8.id = 9
post.responses.default.content.application/json.example.8.value = CHŌMENIDĪS Ch. A.
post.responses.default.content.application/json.example.9.id = 10
post.responses.default.content.application/json.example.9.value = Ī prṓimī othōmanikī́ téchnī kai architektonikī́ stīn Elláda (14os-16os aiṓnas)

[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 100

[expand/exec]
# command should be executable !
command = ./v1/translit/hel/t2/translit_grek.py

[dump]
indent = env('indent', false)
