# These examples can be used directly in VSCode, using REST Client extension (humao.rest-client)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://diseases-ner.services.istex.fr

###
# @name v1diseasesTagger
# Trouve les entités nommées de maladies
POST {{host}}/v1/diseases/tagger?indent=true HTTP/1.1
Content-Type: application/json

[
	{
		"id":1,
		"value": "They have been used in the prevention and treatment of malaria and autoimmune diseases, including systemic lupus erythematosus and rheumatoid arthritis." 
	}
]
