# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.operationId = post-v1-compare-ref
post.summary = Compare une référence bibliographique à une référence issue de Crossref (via son DOI)
post.description = Cette route sert surtout pour la compréhension d'erreurs. Elle prend en entrée une référence et un DOI Crossref. Elle retourne les similarités des différents champs entre la référence issue de Crossref (via le DOI) et entre une référence donnée.
post.tags.0 = biblio-ref
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.requestBody.required = true
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.responses.default.description = Le champ `value` est constitué des différentes composantes d'une référence. Donne pour chaque champs ce qui est trouvé sur crossref et la similarité.
post.parameters.0.description = Indenter le JSON résultant
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean

post.requestBody.content.application/json.example.0.value.doi = 10.1016/j.jelechem.2022.116956
post.requestBody.content.application/json.example.0.value.reference = L.K. Bieniasz, Theory and highly accurate computation of non- limiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes. J. Electroanal. Chem. 895, 115410 (2021)
post.requestBody.content.application/json.example.1.value.reference = L.K. Bieniasz, Theory and highly accurate computation of non- limiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes. J. Electroanal. Chem. 895, 115410 (2021)
post.responses.default.content.application/json.example.0.value.from_crossref.title = Corrigendum to “Theory and highly accurate computation of nonlimiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes” [J. Electroanal. Chem. 895 (2021) 115410]
post.responses.default.content.application/json.example.0.value.from_crossref.first_author_name = Bieniasz
post.responses.default.content.application/json.example.0.value.from_crossref.date = 2022
post.responses.default.content.application/json.example.0.value.from_crossref.source_long = Journal of Electroanalytical Chemistry
post.responses.default.content.application/json.example.0.value.from_crossref.source_short = Journal of Electroanalytical Chemistry
post.responses.default.content.application/json.example.0.value.raw_ref = L.K. Bieniasz, Theory and highly accurate computation of non- limiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes. J. Electroanal. Chem. 895, 115410 (2021)
post.responses.default.content.application/json.example.0.value.matches_scores.title = 0.96
post.responses.default.content.application/json.example.0.value.matches_scores.author = 1
post.responses.default.content.application/json.example.0.value.matches_scores.source_short = 0.64
post.responses.default.content.application/json.example.0.value.matches_scores.source_long = 0.64
post.responses.default.content.application/json.example.0.value.matches_scores.date = 0
post.responses.default.content.application/json.example.1.value.from_crossref.title = Corrigendum to “Theory and highly accurate computation of nonlimiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes” [J. Electroanal. Chem. 895 (2021) 115410]
post.responses.default.content.application/json.example.1.value.from_crossref.first_author_name = Bieniasz
post.responses.default.content.application/json.example.1.value.from_crossref.date = 2022
post.responses.default.content.application/json.example.1.value.from_crossref.source_long = Journal of Electroanalytical Chemistry
post.responses.default.content.application/json.example.1.value.from_crossref.source_short = Journal of Electroanalytical Chemistry
post.responses.default.content.application/json.example.1.value.raw_ref = L.K. Bieniasz, Theory and highly accurate computation of non- limiting chronoamperometric currents for the ErevCirr reaction mechanism at cylindrical wire electrodes. J. Electroanal. Chem. 895, 115410 (2021)
post.responses.default.content.application/json.example.1.value.matches_scores.title = 0.96
post.responses.default.content.application/json.example.1.value.matches_scores.author = 1
post.responses.default.content.application/json.example.1.value.matches_scores.source_short = 0.64
post.responses.default.content.application/json.example.1.value.matches_scores.source_long = 0.64
post.responses.default.content.application/json.example.1.value.matches_scores.date = 0

[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 10

[expand/exec]
# command should be executable !
command = ./v1/compare-ref.py

[dump]
indent = env('indent', false)
