# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://transli-tal.services.istex.fr

###
# @name v1translitCyr
# Translittération de caractères cyrilliques en latin
POST {{host}}/v1/translit/cyr?indent=true HTTP/1.1
Content-Type: application/json

[
    {"id": 1, "value": "долгого ХVIII века"},
    {"id": 2, "value": "Эпоха Просвещения"},
    {"id": 3, "value": "Хороводные и игровые песни Сибири"},
    {"id": 4, "value": "Ежегодник книги СССР"},
    {"id": 5, "value": "Изданiя факультета восточныхъ языковъ императорскаго С.-Петербургскаго университета"},
    {"id": 6, "value": "Публицистика русского зарубежья,1920-1945"},
    {"id": 7, "value": "Современный русский литературный язык"},
    {"id": 8, "value": "Введение в современную российскую историю"},
    {"id": 9, "value": "Вестник истории мировой культуры"},
    {"id": 10, "value": "Журналъ Министерства внутреннихъ дѣлъ"}
]

###
# @name v1translitHelT1
# Translittération de caractères grecs en latin
POST {{host}}/v1/translit/hel/t1?indent=true
content-type: application/json
[
    {"id": 1, "value": "1920-2020: ένας αιώνας δημογραφικής και κοινωνικής εξέλιξης των αιγαιακών κοινωνιών / Βασίλειος Σ. Γαβαλάς"},
    {"id": 2, "value": "Γεωργίου Σ. Φραγκούδη"},
    {"id": 3, "value": "Το ελληνικό χειρόγραφο βιβλίο (12ος-20ος αιώνας)"},
    {"id": 4, "value": "Αιτήματα και πραγματικότητες των Ελλήνων της βενετοκρατίας (1554-1600)"},
    {"id": 5, "value": "Εύθυμα διηγήματα"},
    {"id": 6, "value": "Ο Ούγος Φώσκολος και η Ελληνική Επανάστασις"},
    {"id": 7, "value": "Τροπή των συμφώνων ΤΣ και ΤΖ εις Σ και Ζ εις τα νότια ιδιώματα της νέας ελληνικής"},
    {"id": 8, "value": "ΚΡΙΤΙΚΗ ΕΙΚΑΣΤΙΚΩΝ ΤΕΧΝΩΝ Α ΤΟΜΟΣ"},
    {"id": 9, "value": "ΧΩΜΕΝΙΔΗΣ Χ. Α."},
    {"id": 10, "value": "Η πρώιμη οθωμανική τέχνη και αρχιτεκτονική στην Ελλάδα (14ος-16ος αιώνας)"}
]

###
# @name v1translitHelT2
# Translittération de caractères grecs en latin avec diphtongues
POST {{host}}/v1/translit/hel/t2?indent=true
content-type: application/json
[
    {"id": 1, "value": "1920-2020: ένας αιώνας δημογραφικής και κοινωνικής εξέλιξης των αιγαιακών κοινωνιών / Βασίλειος Σ. Γαβαλάς"},
    {"id": 2, "value": "Γεωργίου Σ. Φραγκούδη"},
    {"id": 3, "value": "Το ελληνικό χειρόγραφο βιβλίο (12ος-20ος αιώνας)"},
    {"id": 4, "value": "Αιτήματα και πραγματικότητες των Ελλήνων της βενετοκρατίας (1554-1600)"},
    {"id": 5, "value": "Εύθυμα διηγήματα"},
    {"id": 6, "value": "Ο Ούγος Φώσκολος και η Ελληνική Επανάστασις"},
    {"id": 7, "value": "Τροπή των συμφώνων ΤΣ και ΤΖ εις Σ και Ζ εις τα νότια ιδιώματα της νέας ελληνικής"},
    {"id": 8, "value": "ΚΡΙΤΙΚΗ ΕΙΚΑΣΤΙΚΩΝ ΤΕΧΝΩΝ Α ΤΟΜΟΣ"},
    {"id": 9, "value": "ΧΩΜΕΝΙΔΗΣ Χ. Α."},
    {"id": 10, "value": "Η πρώιμη οθωμανική τέχνη και αρχιτεκτονική στην Ελλάδα (14ος-16ος αιώνας)"}
]
