POST {{host}}/v1/translit/cyr?indent=true
content-type: application/json
[
    {"id": 1, "value": "долгого ХVIII века"},
    {"id": 2, "value": "Эпоха Просвещения"},
    {"id": 3, "value": "Хороводные и игровые песни Сибири"},
    {"id": 4, "value": "Ежегодник книги СССР"},
    {"id": 5, "value": "Изданiя факультета восточныхъ языковъ императорскаго С.-Петербургскаго университета"},
    {"id": 6, "value": "Публицистика русского зарубежья,1920-1945"},
    {"id": 7, "value": "Современный русский литературный язык"},
    {"id": 8, "value": "Введение в современную российскую историю"},
    {"id": 9, "value": "Вестник истории мировой культуры"},
    {"id": 10, "value": "Журналъ Министерства внутреннихъ дѣлъ"}
]


HTTP 200
[{
    "id": 1,
    "value": "dolgogo XVIII veka"
},
{
    "id": 2,
    "value": "Èpoha Prosveŝeniâ"
},
{
    "id": 3,
    "value": "Horovodnye i igrovye pesni Sibiri"
},
{
    "id": 4,
    "value": "Ežegodnik knigi SSSR"
},
{
    "id": 5,
    "value": "Izdanìâ fakulʹteta vostočnyhʺ âzykovʺ imperatorskago S.-Peterburgskago universiteta"
},
{
    "id": 6,
    "value": "Publicistika russkogo zarubežʹâ,1920-1945"
},
{
    "id": 7,
    "value": "Sovremennyj russkij literaturnyj âzyk"
},
{
    "id": 8,
    "value": "Vvedenie v sovremennuû rossijskuû istoriû"
},
{
    "id": 9,
    "value": "Vestnik istorii mirovoj kulʹtury"
},
{
    "id": 10,
    "value": "Žurnalʺ Ministerstva vnutrennihʺ dělʺ"
}]

#####################################################################
POST {{host}}/v1/translit/hel/t1?indent=true
content-type: application/json
[
    {"id": 1, "value": "1920-2020: ένας αιώνας δημογραφικής και κοινωνικής εξέλιξης των αιγαιακών κοινωνιών / Βασίλειος Σ. Γαβαλάς"},
    {"id": 2, "value": "Γεωργίου Σ. Φραγκούδη"},
    {"id": 3, "value": "Το ελληνικό χειρόγραφο βιβλίο (12ος-20ος αιώνας)"},
    {"id": 4, "value": "Αιτήματα και πραγματικότητες των Ελλήνων της βενετοκρατίας (1554-1600)"},
    {"id": 5, "value": "Εύθυμα διηγήματα"},
    {"id": 6, "value": "Ο Ούγος Φώσκολος και η Ελληνική Επανάστασις"},
    {"id": 7, "value": "Τροπή των συμφώνων ΤΣ και ΤΖ εις Σ και Ζ εις τα νότια ιδιώματα της νέας ελληνικής"},
    {"id": 8, "value": "ΚΡΙΤΙΚΗ ΕΙΚΑΣΤΙΚΩΝ ΤΕΧΝΩΝ Α ΤΟΜΟΣ"},
    {"id": 9, "value": "ΧΩΜΕΝΙΔΗΣ Χ. Α."},
    {"id": 10, "value": "Η πρώιμη οθωμανική τέχνη και αρχιτεκτονική στην Ελλάδα (14ος-16ος αιώνας)"}
]

HTTP 200
[{
    "id": 1,
    "value": "1920-2020: énas aiṓnas dīmografikī́s kai koinōnikī́s exélixīs tōn aigaiakṓn koinōniṓn / Vasíleios S. Gavalás"
},
{
    "id": 2,
    "value": "Geōrgíoy S. Fragkoýdī"
},
{
    "id": 3,
    "value": "To ellīnikó cheirógrafo vivlío (12os-20os aiṓnas)"
},
{
    "id": 4,
    "value": "Aitī́mata kai pragmatikótītes tōn Ellī́nōn tīs venetokratías (1554-1600)"
},
{
    "id": 5,
    "value": "Eýthyma diīgī́mata"
},
{
    "id": 6,
    "value": "O Oýgos Fṓskolos kai ī Ellīnikī́ Epanástasis"
},
{
    "id": 7,
    "value": "Tropī́ tōn symfṓnōn TS kai TZ eis S kai Z eis ta nótia idiṓmata tīs néas ellīnikī́s"
},
{
    "id": 8,
    "value": "KRITIKĪ EIKASTIKŌN TECHNŌN A TOMOS"
},
{
    "id": 9,
    "value": "CHŌMENIDĪS Ch. A."
},
{
    "id": 10,
    "value": "Ī prṓimī othōmanikī́ téchnī kai architektonikī́ stīn Elláda (14os-16os aiṓnas)"
}]

#####################################################################
POST {{host}}/v1/translit/hel/t2?indent=true
content-type: application/json
[
    {"id": 1, "value": "1920-2020: ένας αιώνας δημογραφικής και κοινωνικής εξέλιξης των αιγαιακών κοινωνιών / Βασίλειος Σ. Γαβαλάς"},
    {"id": 2, "value": "Γεωργίου Σ. Φραγκούδη"},
    {"id": 3, "value": "Το ελληνικό χειρόγραφο βιβλίο (12ος-20ος αιώνας)"},
    {"id": 4, "value": "Αιτήματα και πραγματικότητες των Ελλήνων της βενετοκρατίας (1554-1600)"},
    {"id": 5, "value": "Εύθυμα διηγήματα"},
    {"id": 6, "value": "Ο Ούγος Φώσκολος και η Ελληνική Επανάστασις"},
    {"id": 7, "value": "Τροπή των συμφώνων ΤΣ και ΤΖ εις Σ και Ζ εις τα νότια ιδιώματα της νέας ελληνικής"},
    {"id": 8, "value": "ΚΡΙΤΙΚΗ ΕΙΚΑΣΤΙΚΩΝ ΤΕΧΝΩΝ Α ΤΟΜΟΣ"},
    {"id": 9, "value": "ΧΩΜΕΝΙΔΗΣ Χ. Α."},
    {"id": 10, "value": "Η πρώιμη οθωμανική τέχνη και αρχιτεκτονική στην Ελλάδα (14ος-16ος αιώνας)"}
]

HTTP 200
[{
    "id": 1,
    "value": "1920-2020: énas aiṓnas dīmografikī́s kai koinōnikī́s exélixīs tōn aigaiakṓn koinōniṓn / Vasíleios S. Gavalás"
},
{
    "id": 2,
    "value": "Geōrgíou S. Fragkoúdī"
},
{
    "id": 3,
    "value": "To ellīnikó cheirógrafo vivlío (12os-20os aiṓnas)"
},
{
    "id": 4,
    "value": "Aitī́mata kai pragmatikótītes tōn Ellī́nōn tīs venetokratías (1554-1600)"
},
{
    "id": 5,
    "value": "Éfthyma diīgī́mata"
},
{
    "id": 6,
    "value": "O Oúgos Fṓskolos kai ī Ellīnikī́ Epanástasis"
},
{
    "id": 7,
    "value": "Tropī́ tōn symfṓnōn TS kai TZ eis S kai Z eis ta nótia idiṓmata tīs néas ellīnikī́s"
},
{
    "id": 8,
    "value": "KRITIKĪ EIKASTIKŌN TECHNŌN A TOMOS"
},
{
    "id": 9,
    "value": "CHŌMENIDĪS Ch. A."
},
{
    "id": 10,
    "value": "Ī prṓimī othōmanikī́ téchnī kai architektonikī́ stīn Elláda (14os-16os aiṓnas)"
}]
