# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.summary = Classification hiérarchique Openalex
post.description = Le web service classe automatiquement des documents scientifiques en anglais dans le premier et deuxième niveau de la classification Openalex à partir de leur résumé. Attention : si les résumés sont trop courts, le risque d'erreur est augmenté.
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.tags.0 = openalex-classification
post.requestBody.required = true
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean
post.parameters.0.description = Indent or not the JSON Result

# Examples



[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 100

[expand/exec]
# command should be executable !
command = ./v1/classif.py

[dump]
indent = env('indent', false)
