# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://coara-tools.services.istex.fr

###
# @name v1tools
# Extraction d'outils
POST {{host}}/v1/tools?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "Reforming Research Assessment at Strathclyde: A five-year CoARA action plan Background Strathclyde is committed to enabling research activity that adheres to the highest standards of research integrity, underpinned by a positive research culture. Following seminal initiatives such as the San Francisco Declaration on Research Assessment (DORA, 2013), the Leiden Manifesto (2015) and the Metric Tide Report (2016), there is now broad agreement amongst the research community that reform of research assessment is required to promote sustainable research quality and strengthen research cultures." }
]
