POST {{host}}/v1/tools?indent=true
content-type: application/json
[
	{ "value": "Reforming Research Assessment at Strathclyde: A five-year CoARA action plan Background Strathclyde is committed to enabling research activity that adheres to the highest standards of research integrity, underpinned by a positive research culture. Following seminal initiatives such as the San Francisco Declaration on Research Assessment (DORA, 2013), the Leiden Manifesto (2015) and the Metric Tide Report (2016), there is now broad agreement amongst the research community that reform of research assessment is required to promote sustainable research quality and strengthen research cultures." }
]


HTTP 200
[{
    "value": [
        {
            "tool": "research integrity",
            "tool_homogenised": "research integrity",
            "other_tool_form": [
                "research integrity",
                "research integrity code",
                "research integrity practices"
            ],
            "definition": "definition of research integrity"
        },
        {
            "tool": "san francisco declaration on research assessment",
            "tool_homogenised": "dora",
            "other_tool_form": [
                "dora",
                "declaration on research assessment",
                "san francisco declaration on research assessment"
            ],
            "definition": "Definition of dora"
        },
        {
            "tool": "dora",
            "tool_homogenised": "dora",
            "other_tool_form": [
                "dora",
                "declaration on research assessment",
                "san francisco declaration on research assessment"
            ],
            "definition": "Definition of dora"
        },
        {
            "tool": "leiden manifesto",
            "tool_homogenised": "leiden manifesto",
            "other_tool_form": [
                "leiden manifesto"
            ],
            "definition": "Definition of leiden manifesto"
        }
    ]
}]