# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://embeddings-computer.services.istex.fr

###
# @name v1embedSmallText
# Calcule les embeddings de petits textes (sans les découper)
POST {{host}}/v1/embed-small-text?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "This is a test text for the embeddings model. It should be able to handle multiple texts at once." },
	{ "value": "Et maintenant, je mets une phrase en français." }
]
