# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://data-topcitation.services.istex.fr

###
# @name v1TopCitation
# Renvoie le top 10 des citations phares d'un corpus
POST {{host}}/v1/topcitation?indent=true HTTP/1.1
Content-Type: application/x-gzip
X-Webhook-Success: https://webhook.site/7b9ddc51-b3eb-447a-8eba-1ab13f016bb7
X-Webhook-Failure: https://webhook.site/7b9ddc51-b3eb-447a-8eba-1ab13f016bb7

< ./examples/list-doi.tar.gz
