# These examples can be used directly in VSCode, using REST Client extension (humao.rest-client)

# Décommenter/commenter les lignes voulues pour tester localement
@baseUrl=http://localhost:31976
# @baseUrl=https://base-line.services.istex.fr

###
# @name v1NoAccent
# Supprime les accents dans le champ value
POST {{baseUrl}}/v1/no-accent?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "à l'école" },
	{ "value": "où" }
]

###
# @name v1NoAccent2
# Supprime les accents dans le champ value
POST {{baseUrl}}/v1/no-accent2?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "à l'école" },
	{ "value": "où" }
]

###
# @name v1EchoJson
# Supprime les accents dans le champ value
POST {{baseUrl}}/v1/echo/json?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "à l'école" },
	{ "value": "où" }
]

###
# @name v1EchoCsv
# Interprète le CSV et le renvoie (avec un séparateur ;)
POST {{baseUrl}}/v1/echo/csv HTTP/1.1
Content-Type: text/csv

a,b
1,2
###
# @name v1EchoRaw
# Renvoie le texte envoyé
POST {{baseUrl}}/v1/echo/raw HTTP/1.1
Content-Type: text/plain

Ceci est le texte envoyé.
###
# @name v1TrueCsv
# Renvoie true pour le champ value
POST {{baseUrl}}/v1/true/csv HTTP/1.1
Content-Type: text/csv

a,value
1,2
###
# @name v1TrueJson
# Renvoie true pour le champ value
POST {{baseUrl}}/v1/true/json HTTP/1.1
Content-Type: application/json

[
	{ "value": "à l'école" },
	{ "value": "où" }
]

###