# OpenAPI Documentation - JSON format (dot notation)
mimeType = application/json

post.summary = Vérifie si un document OpenAlex est un document de recherche ou non
post.description = A partir d'un identifiant OpenAlex ou des métadonnées d'un document, le service établie si c'est un document de recherche ou non
post.tags.0 = openalex-doctype
post.responses.default.content.application/json.schema.$ref =  #/components/schemas/JSONStream
post.requestBody.required = true
post.requestBody.content.application/json.schema.$ref = #/components/schemas/JSONStream
post.parameters.0.in = query
post.parameters.0.name = indent
post.parameters.0.schema.type = boolean
post.parameters.0.description = Indent or not the JSON Result

# Examples
post.requestBody.content.application/json.example.0.value = w4405561029
post.requestBody.content.application/json.example.1.value = w4405561030
post.requestBody.content.application/json.example.2.value = not an ID
post.responses.default.content.application/json.example.0.value.isResearchDoc = false
post.responses.default.content.application/json.example.0.value.score = 0.72
post.responses.default.content.application/json.example.1.value.isResearchDoc = true
post.responses.default.content.application/json.example.1.value.score = 1
post.responses.default.content.application/json.example.2.value.isResearchDoc = null
post.responses.default.content.application/json.example.2.value.score = null
;'

[use]
plugin = @ezs/spawn
plugin = @ezs/basics

[JSONParse]
separator = *

[expand]
path = value
size = 10

[expand/exec]
# command should be executable !
command = ./v1/isresearch-id.py

[dump]
indent = env('indent', false)
