# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://astro-ner.services.istex.fr

###
# @name v1Tagger
# Description de la route
POST {{host}}/v1/tagger?indent=true HTTP/1.1
Content-Type: application/json

[
	{ "value": "V643 Orionis is a binary star system located in the Orion constellation, offering valuable insightsinto stellar evolution" }
	]
