# These examples can be used directly in VSCode, using HTTPYac extension (anweber.vscode-httpyac)
# They are important, because used to generate the tests.hurl file.

# Décommenter/commenter les lignes voulues pour tester localement
@host=http://localhost:31976
# @host=https://sciencemetrix-classification.services.istex.fr

###
# @name v1classif
# Classification en domaines scientifiques Science-Metrix
POST {{host}}/v1/classif?indent=true HTTP/1.1
Content-Type: application/json

[
	{"id": "1", "value": "anatomical comparison between compression wood and opposite wood in a branch of korean pine pinus koraiensis compression wood and opposite wood formed in the branch of korean pine pinus koraiensis s et z is described and compared in qualitative and quantitative anatomical aspects" }
]
