POST {{host}}/v1/classif?indent=true
content-type: application/json
[
	{"id": "1", "value": "anatomical comparison between compression wood and opposite wood in a branch of korean pine pinus koraiensis compression wood and opposite wood formed in the branch of korean pine pinus koraiensis s et z is described and compared in qualitative and quantitative anatomical aspects" }
]


HTTP 200
[{
    "id": "1",
    "value": {
        "domain": "Forestry"
    }
}]