POST {{host}}/v1/expand?indent=true
content-type: application/json
[
  { "value": "Baran, N (reprint author), Univ Zagreb, Dept Phys, Bijenieka Cesta 32, Zagreb 10000, Croatia."},
  { "value": "Harikane, Y (reprint author), Univ Tokyo, Inst Cosm Ray Res, 5-1-5 Kashiwanoha, Kashiwa, Chiba 2778582, Japan.; Harikane, Y (reprint author), Univ Tokyo, Grad Sch Sci, Dept Phys, Bunkyo Ku, 7-3-1 Hongo, Tokyo 1130033, Japan."},
  { "value": "Davidzon, I (reprint author), Aix Marseille Univ, LAM, CNRS, UMR 7326, F-13388 Marseille, France.; Davidzon, I (reprint author), INAF Osservatorio Astron Bologna, Via Ranzani 1, I-40127 Bologna, Italy."},
  { "value": "Zolotukhin, I (reprint author), IRAP, CNRS, 9 Ave Colonel Roche,BP 44346, F-31028 Toulouse 4, France.; Zolotukhin, I (reprint author), Moscow MV Lomonosov State Univ, Sternberg Astron Inst, Univ Skij Pr 13, Moscow 119992, Russia."},
  { "value": "Cooke, J (reprint author), Swinburne Univ Technol, Ctr Astrophys & Supercomp, Hawthorn, Vic 3122, Australia."},
  { "value": "van Uitert, E (reprint author), Argelander Inst Astron, Hugel 71, D-53121 Bonn, Germany."},
  { "value": "Harnois-Deraps, J (reprint author), Univ British Columbia, Dept Phys & Astron, Vancouver, BC V6T 1Z1, Canada."},
  { "value": "Ford, J (reprint author), Univ British Columbia, Dept Phys & Astron, 6224 Agr Rd, Vancouver, BC V6T 1Z1, Canada."},
  { "value": "Laigle, C (reprint author), Univ Paris 06, Sorbonne Univ, 98b Bd Arago, F-75014 Paris, France.; Laigle, C (reprint author), CNRS, UMR 7095, IAP, 98b Bd Arago, F-75014 Paris, France."}
]

HTTP 200
[{
    "value": {
        "house": "baran n reprint author univ zagreb dept phys bijenieka",
        "road": "cesta",
        "house_number": "32",
        "city": "zagreb",
        "postcode": "10000",
        "country": {
            "cartographyCode": "HRV",
            "about": "http://data.loterre.fr/ark:/67375/9SD-BM4704K2-7",
            "prefLabel@fr": "Croatie",
            "prefLabel@en": "Croatia",
            "wikidataURI": "https://www.wikidata.org/wiki/Q1435",
            "geonameURI": "https://www.geonames.org/3202326",
            "countryCode": "HR",
            "latitude": "45.0162343679711",
            "longitude": "16.5661911066622",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Baran, N (reprint author), Univ Zagreb, Dept Phys, Bijenieka Cesta 32, Zagreb 10000, Croatia."
    }
},
{
    "value": {
        "house": "harikane y reprint author univ tokyo grad sch sci dept phys",
        "house_number": "5-1-5",
        "road": "kashiwanoha",
        "city": "tokyo",
        "state": "chiba",
        "postcode": "1130033",
        "country": {
            "cartographyCode": "JPN",
            "about": "http://data.loterre.fr/ark:/67375/9SD-T7D7448F-7",
            "prefLabel@fr": "Japon",
            "prefLabel@en": "Japan",
            "wikidataURI": "https://www.wikidata.org/wiki/Q1490",
            "geonameURI": "https://www.geonames.org/1861060",
            "countryCode": "JP",
            "latitude": "36.019075365944",
            "longitude": "136.881947315984",
            "localization@en": [],
            "localization@fr": []
        },
        "city_district": "hongo",
        "id": "Harikane, Y (reprint author), Univ Tokyo, Inst Cosm Ray Res, 5-1-5 Kashiwanoha, Kashiwa, Chiba 2778582, Japan.; Harikane, Y (reprint author), Univ Tokyo, Grad Sch Sci, Dept Phys, Bunkyo Ku, 7-3-1 Hongo, Tokyo 1130033, Japan."
    }
},
{
    "value": {
        "house": "france. davidzon i reprint author inaf osservatorio astron bologna",
        "house_number": "1",
        "postcode": "i-40127",
        "city": "bologna",
        "road": "via ranzani",
        "country": {
            "cartographyCode": "ITA",
            "about": "http://data.loterre.fr/ark:/67375/9SD-D7887R60-W",
            "prefLabel@fr": "Italie",
            "prefLabel@en": "Italy",
            "wikidataURI": "https://www.wikidata.org/wiki/Q220",
            "geonameURI": "https://www.geonames.org/3175395",
            "countryCode": "IT",
            "latitude": "43.472476107586",
            "longitude": "12.2194764873985",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Davidzon, I (reprint author), Aix Marseille Univ, LAM, CNRS, UMR 7326, F-13388 Marseille, France.; Davidzon, I (reprint author), INAF Osservatorio Astron Bologna, Via Ranzani 1, I-40127 Bologna, Italy."
    }
},
{
    "value": {
        "house": "france. zolotukhin i reprint author moscow mv lomonosov state univ sternberg astron inst univ skij",
        "house_number": "9",
        "road": "pr 13",
        "po_box": "bp 44346",
        "postcode": "119992",
        "city": "moscow",
        "country": {
            "cartographyCode": "RUS",
            "about": "http://data.loterre.fr/ark:/67375/9SD-MTZLFXTZ-X",
            "prefLabel@fr": "Russie",
            "prefLabel@en": "Russia",
            "wikidataURI": "https://www.wikidata.org/wiki/Q649",
            "geonameURI": "https://www.geonames.org/2017370",
            "countryCode": "RU",
            "latitude": "61.6925647074082",
            "longitude": "99.2165267869251",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Zolotukhin, I (reprint author), IRAP, CNRS, 9 Ave Colonel Roche,BP 44346, F-31028 Toulouse 4, France.; Zolotukhin, I (reprint author), Moscow MV Lomonosov State Univ, Sternberg Astron Inst, Univ Skij Pr 13, Moscow 119992, Russia."
    }
},
{
    "value": {
        "house": "cooke j reprint author swinburne univ technol ctr astrophys & supercomp",
        "suburb": "hawthorn",
        "state": "vic",
        "postcode": "3122",
        "country": {
            "cartographyCode": "AUS",
            "about": "http://data.loterre.fr/ark:/67375/9SD-VFP5KTPK-R",
            "prefLabel@fr": "Australie",
            "prefLabel@en": "Australia",
            "wikidataURI": "https://www.wikidata.org/wiki/Q3114",
            "geonameURI": "https://www.geonames.org/2077456",
            "countryCode": "AU",
            "latitude": "-25.5607640622395",
            "longitude": "134.376078573618",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Cooke, J (reprint author), Swinburne Univ Technol, Ctr Astrophys & Supercomp, Hawthorn, Vic 3122, Australia."
    }
},
{
    "value": {
        "house": "van uitert e reprint author argelander inst astron",
        "road": "hugel",
        "house_number": "71",
        "postcode": "d-53121",
        "city": "bonn",
        "country": {
            "cartographyCode": "DEU",
            "about": "http://data.loterre.fr/ark:/67375/9SD-HM2MMZDZ-0",
            "prefLabel@fr": "Allemagne",
            "prefLabel@en": "Germany",
            "wikidataURI": "https://www.wikidata.org/wiki/Q64",
            "geonameURI": "https://www.geonames.org/2921044",
            "countryCode": "DE",
            "latitude": "51.1337226904078",
            "longitude": "10.2884850927429",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "van Uitert, E (reprint author), Argelander Inst Astron, Hugel 71, D-53121 Bonn, Germany."
    }
},
{
    "value": {
        "house": "harnois-deraps j reprint author univ british columbia dept phys & astron",
        "city": "vancouver",
        "state": "bc",
        "postcode": "v6t 1z1",
        "country": {
            "cartographyCode": "CAN",
            "about": "http://data.loterre.fr/ark:/67375/9SD-QDWJ08N6-7",
            "prefLabel@fr": "Canada",
            "prefLabel@en": "Canada",
            "wikidataURI": "https://www.wikidata.org/wiki/Q1930",
            "geonameURI": "https://www.geonames.org/6251999",
            "countryCode": "CA",
            "latitude": "57.7487688035733",
            "longitude": "-101.569822125212",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Harnois-Deraps, J (reprint author), Univ British Columbia, Dept Phys & Astron, Vancouver, BC V6T 1Z1, Canada."
    }
},
{
    "value": {
        "house": "ford j reprint author univ british columbia dept phys & astron",
        "house_number": "6224",
        "road": "agr rd",
        "city": "vancouver",
        "state": "bc",
        "postcode": "v6t 1z1",
        "country": {
            "cartographyCode": "CAN",
            "about": "http://data.loterre.fr/ark:/67375/9SD-QDWJ08N6-7",
            "prefLabel@fr": "Canada",
            "prefLabel@en": "Canada",
            "wikidataURI": "https://www.wikidata.org/wiki/Q1930",
            "geonameURI": "https://www.geonames.org/6251999",
            "countryCode": "CA",
            "latitude": "57.7487688035733",
            "longitude": "-101.569822125212",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Ford, J (reprint author), Univ British Columbia, Dept Phys & Astron, 6224 Agr Rd, Vancouver, BC V6T 1Z1, Canada."
    }
},
{
    "value": {
        "house": "france. laigle c reprint author cnrs umr 7095",
        "house_number": "98b",
        "road": "bd arago",
        "postcode": "f-75014",
        "city": "paris",
        "country": {
            "cartographyCode": "FRA",
            "about": "http://data.loterre.fr/ark:/67375/9SD-WNLFZ7TZ-K",
            "prefLabel@fr": "France",
            "prefLabel@en": "France",
            "wikidataURI": "https://www.wikidata.org/wiki/Q90",
            "geonameURI": "https://www.geonames.org/3017382",
            "countryCode": "FR",
            "latitude": "46.6064633728632",
            "longitude": "2.33908864602935",
            "localization@en": [],
            "localization@fr": []
        },
        "id": "Laigle, C (reprint author), Univ Paris 06, Sorbonne Univ, 98b Bd Arago, F-75014 Paris, France.; Laigle, C (reprint author), CNRS, UMR 7095, IAP, 98b Bd Arago, F-75014 Paris, France."
    }
}]

POST {{host}}/v1/rnsr/json?indent=true
content-type: application/json
[
  { "id":1, "value": { "year": "2021", "address": "CNRS UMR AMAP MONTPELLIER FRA" } },
  { "id":2, "value": { "year": "2021", "address": "IRD UMR AMAP MONTPELLIER FRA" } },
  { "id":3, "value": { "year": "2021", "address": "University of Bordeaux, IMS, CNRS UMR5218, Talence, F-33405, France" } },
  { "id":4, "value": { "year": "2021", "address": "CENBG, CNRS/IN2P3, Chemin du Solarium B. P. 120, Gradignan, F-33175, France" } },
  { "id":5, "value": { "year": "2021", "address": "Nulle part" } },
  { "id":6, "value": { "address": "Intemporel" } },
  { "id":7, "value": { "address": "Inist-CNRS, UPS76, 2 rue Jean Zay, Vandoeuvre-lès-Nancy" } }
]

HTTP 200
[{
    "id": 1,
    "value": [
        "200317641S"
    ]
},
{
    "id": 2,
    "value": [
        "200317641S"
    ]
},
{
    "id": 3,
    "value": [
        "200711887V"
    ]
},
{
    "id": 4,
    "value": []
},
{
    "id": 5,
    "value": []
},
{
    "id": 6,
    "value": []
},
{
    "id": 7,
    "value": [
        "198822446E"
    ]
}]

POST {{host}}/v1/rnsr/info?indent=true
content-type: application/json
[
  { "id":1, "value": { "year": "2021", "address": "CNRS UMR AMAP MONTPELLIER FRA" } },
  { "id":3, "value": { "year": "2021", "address": "University of Bordeaux, IMS, CNRS UMR5218, Talence, F-33405, France" } },
  { "id":4, "value": { "year": "2021", "address": "CENBG, CNRS/IN2P3, Chemin du Solarium B. P. 120, Gradignan, F-33175, France" } },
  { "id":5, "value": { "year": "2021", "address": "Nulle part" } },
  { "id":6, "value": { "address": "Intemporel" } },
  { "id":7, "value": { "address": "Inist-CNRS, UPS76, 2 rue Jean Zay, Vandoeuvre-lès-Nancy" } }
]

HTTP 200
[{
    "id": 1,
    "value": [
        {
            "num_nat_struct": "200317641S",
            "intitule": "botAnique et Modélisation de l'Architecture des Plantes et des végétations",
            "sigle": "AMAP",
            "ville_postale": "MONTPELLIER CEDEX 5",
            "code_postal": 34398,
            "etabAssoc": [
                {
                    "etab": {
                        "sigle": "CNRS",
                        "libelle": "Centre national de la recherche scientifique",
                        "sigleAppauvri": "cnrs",
                        "libelleAppauvri": "centre national de la recherche scientifique"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5120
                },
                {
                    "etab": {
                        "sigle": "IRD",
                        "libelle": "Institut de recherche pour le developpement",
                        "sigleAppauvri": "ird",
                        "libelleAppauvri": "institut de recherche pour le developpement"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5120
                },
                {
                    "etab": {
                        "sigle": "CIRAD",
                        "libelle": "Centre de Cooperation Internationale en Recherche Agronomique pour le Developpement",
                        "sigleAppauvri": "cirad",
                        "libelleAppauvri": "centre de cooperation internationale en recherche agronomique pour le developpement"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 51
                },
                {
                    "etab": {
                        "sigle": "MONTPELLIER",
                        "libelle": "Université de Montpellier (EPE)",
                        "sigleAppauvri": "montpellier",
                        "libelleAppauvri": "universite de montpellier (epe)"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5120
                },
                {
                    "etab": {
                        "sigle": "INRAE",
                        "libelle": "Institut national de recherche pour l'agriculture, l'alimentation et l'environnement",
                        "sigleAppauvri": "inrae",
                        "libelleAppauvri": "institut national de recherche pour l agriculture, l alimentation et l environnement"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 931
                }
            ],
            "intituleAppauvri": "botanique et modelisation de l architecture des plantes et des vegetations",
            "sigleAppauvri": "amap",
            "ville_postale_appauvrie": "montpellier cedex 5",
            "annee_creation": 2001,
            "an_fermeture": 0
        }
    ]
},
{
    "id": 3,
    "value": [
        {
            "num_nat_struct": "200711887V",
            "intitule": "Laboratoire d'intégration du matériau au système",
            "sigle": "IMS",
            "ville_postale": "TALENCE CEDEX",
            "code_postal": 33405,
            "etabAssoc": [
                {
                    "etab": {
                        "sigle": "CNRS",
                        "libelle": "Centre national de la recherche scientifique",
                        "sigleAppauvri": "cnrs",
                        "libelleAppauvri": "centre national de la recherche scientifique"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5218
                },
                {
                    "etab": {
                        "sigle": "BORDEAUX",
                        "libelle": "Université de Bordeaux",
                        "sigleAppauvri": "bordeaux",
                        "libelleAppauvri": "universite de bordeaux"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5218
                },
                {
                    "etab": {
                        "sigle": "Bordeaux INP",
                        "libelle": "Institut Polytechnique Bordeaux",
                        "sigleAppauvri": "bordeaux inp",
                        "libelleAppauvri": "institut polytechnique bordeaux"
                    },
                    "label": "UMR",
                    "labelAppauvri": "umr",
                    "numero": 5218
                }
            ],
            "intituleAppauvri": "laboratoire d integration du materiau au systeme",
            "sigleAppauvri": "ims",
            "ville_postale_appauvrie": "talence cedex",
            "annee_creation": 2006,
            "an_fermeture": 0
        }
    ]
},
{
    "id": 4,
    "value": []
},
{
    "id": 5,
    "value": []
},
{
    "id": 6,
    "value": []
},
{
    "id": 7,
    "value": [
        {
            "num_nat_struct": "198822446E",
            "intitule": "Institut de l'information scientifique et technique",
            "sigle": "INIST",
            "ville_postale": "VANDOEUVRE LES NANCY CEDEX",
            "code_postal": 54519,
            "etabAssoc": [
                {
                    "etab": {
                        "sigle": "CNRS",
                        "libelle": "Centre national de la recherche scientifique",
                        "sigleAppauvri": "cnrs",
                        "libelleAppauvri": "centre national de la recherche scientifique"
                    },
                    "label": "UAR",
                    "labelAppauvri": "uar",
                    "numero": 76
                }
            ],
            "intituleAppauvri": "institut de l information scientifique et technique",
            "sigleAppauvri": "inist",
            "ville_postale_appauvrie": "vandoeuvre les nancy cedex",
            "annee_creation": 1988,
            "an_fermeture": 0
        }
    ]
}]

POST {{host}}/v1/rnsr/csv
content-type: text/csv
```
Année,Adresse
2015,CNRS UMR AMAP MONTPELLIER FRA
2015,IRD UMR AMAP MONTPELLIER FRA
2015,"University of Bordeaux, IMS, CNRS UMR5218, Talence, F-33405, France"
2015,"CENBG, CNRS/IN2P3, Chemin du Solarium B. P. 120, Gradignan, F-33175, France"
```

HTTP 200
[Asserts]
body contains "Année;Adresse;RNSR"
body contains "2015;CNRS UMR AMAP MONTPELLIER FRA;200317641S"
body contains "2015;IRD UMR AMAP MONTPELLIER FRA;200317641S"
body contains "2015;University of Bordeaux, IMS, CNRS UMR5218, Talence, F-33405, France;200711887V"
body contains "2015;CENBG, CNRS/IN2P3, Chemin du Solarium B. P. 120, Gradignan, F-33175, France;"
#```
#Année;Adresse;RNSR
#2015;CNRS UMR AMAP MONTPELLIER FRA;200317641S
#2015;IRD UMR AMAP MONTPELLIER FRA;200317641S
#2015;University of Bordeaux, IMS, CNRS UMR5218, Talence, F-33405, France;200711887V
#2015;CENBG, CNRS/IN2P3, Chemin du Solarium B. P. 120, Gradignan, F-33175, France;
#```

POST {{host}}/v1/rnsr/conditor
content-type: application/json
[{
  "xPublicationDate": ["2012-01-01"],
  "authors": [{
    "affiliations": [{
      "address": "GDR 2989 Université Versailles Saint-Quentin-en-Yvelines, 63009"
    }]
  }]
}]

HTTP 200
[{
    "xPublicationDate": [
        "2012-01-01"
    ],
    "authors": [
        {
            "affiliations": [
                {
                    "address": "GDR 2989 Université Versailles Saint-Quentin-en-Yvelines, 63009",
                    "conditorRnsr": [
                        "200619958X"
                    ]
                }
            ]
        }
    ]
}]

POST {{host}}/v1/addresses/parse?indent=true
content-type: application/json
[
  {
    "value": "Barboncino 781 Franklin Ave, Crown Heights, Brooklyn, NY 11238"
  }
]

HTTP 200
[{
    "value": {
        "id": "Barboncino 781 Franklin Ave, Crown Heights, Brooklyn, NY 11238",
        "value": {
            "house": "barboncino",
            "house_number": "781",
            "road": "franklin ave",
            "suburb": "crown heights",
            "city_district": "brooklyn",
            "state": "ny",
            "postcode": "11238"
        }
    }
}]

POST {{host}}/v1/addresses/normalize?indent=true
content-type: application/json
[
  {
    "value": "Barboncino 781 Franklin Ave, Crown Heights, Brooklyn, NY 11238"
  }
]

HTTP 200
[{
    "value": {
        "id": "Barboncino 781 Franklin Ave, Crown Heights, Brooklyn, NY 11238",
        "value": [
            "barboncino 781 franklin avenue crown heights brooklyn ny 11238",
            "barboncino 781 franklin avenue crown heights brooklyn new york 11238"
        ]
    }
}]

POST {{host}}/v1/ror/get-id?indent=true
content-type: application/json
[
  {
    "id": 1,
    "status": "wrong",
    "value": "Norwich Medical School, University of East Anglia"
  },
  {
    "id": 2,
    "status": "correct",
    "value": "Institut Lumière Matière [Villeurbanne]"
  },
  {
    "id": 3,
    "status": "correct-2",
    "value": "NSF's National Optical-Infrared Astronomy Research Laboratory, 950 North Cherry Avenue, Tucson, AZ 85719, USA"
  },
  {
    "id": 4,
    "status": "non-existing",
    "value": "Sphere Energy SAS, 250 Bis Boulevard Saint Germain, 75007, Paris, France"
  },
  {
    "id": 5,
    "status": "non-existing",
    "value" : "Department of Computational Engineering, CSC — Scientific Computing Ltd, P.O. Box 405, 02101, Espoo, Finland"
  }
]

HTTP 200
[{
    "id": 1,
    "status": "wrong",
    "value": {
        "id_ror": "https://ror.org/01e0ns064",
        "score": 1,
        "name": "University of East",
        "type": [
            "Education"
        ],
        "name_geonames": null,
        "id_geonames": null
    }
},
{
    "id": 2,
    "status": "correct",
    "value": {
        "id_ror": "https://ror.org/0323bey33",
        "score": 0.79,
        "name": "Institut Lumière Matière",
        "type": [
            "Facility"
        ],
        "name_geonames": null,
        "id_geonames": null
    }
},
{
    "id": 3,
    "status": "correct-2",
    "value": {
        "id_ror": "https://ror.org/03zmsge54",
        "score": 1,
        "name": "NSF’s NOIRLab",
        "type": [
            "Facility"
        ],
        "name_geonames": "Pima",
        "id_geonames": 5308878
    }
},
{
    "id": 4,
    "status": "non-existing",
    "value": "No match found"
},
{
    "id": 5,
    "status": "non-existing",
    "value": "No match found"
}]