# .github/workflows/docker-build-on-push.yml

name: Build & Test

on:
  push:
    branches:
      - "services/*/*"
    paths-ignore:
      - "**.md"
      - "**/swagger.json"

jobs:
  test-on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from Git
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/5.0.1/hurl_5.0.1_amd64.deb
          sudo dpkg -i hurl_5.0.1_amd64.deb
          hurl --version

      - name: Build .env from Github Actions secrets
        shell: bash
        run: |
          bin/create-env.sh ${{ github.ref_name }} ${{ secrets.WEBDAV_LOGIN }} ${{ secrets.WEBDAV_PASSWORD }} ${{ secrets.WEBDAV_URL }} ${{secrets.OPENALEX_API_KEY}} ${{secrets.UNPAYWALL_API_KEY}} ${{secrets.CROSSREF_API_KEY}} ${{secrets.KAGGLE_USERNAME}} ${{secrets.KAGGLE_KEY}}
          ls -l services/*/.env

      - name: Build Docker Image & Test
        shell: bash
        run: |
          bin/test-on-branch.sh ${{ github.ref_name }}
